language: node_js
node_js:
  - "5.5"
#before_install:
#  - sudo apt-get install -y mongodb-org
before_script:
  - npm install grunt-cli -g
  - npm install jasmine-node -g
  - npm install
#  - node iris.js site=default
  - mongo mydb_test --eval 'db.addUser("travis", "test");'
  - service mongod status
services:
  - mongodb
env: site=default
